[package]
name = "nbt-compress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = { version = "1.0.28", features = ["zlib-ng"] }
zopfli = { version = "0.8.0", features = ["gzip"] }